pipeline:
  identifier: Build_rohannaik29_java_hello_world_with_maven_1701588761708
  name: Build java-hello-world-with-maven
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: rohannaik29/java-hello-world-with-maven
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: compile
                  spec:
                    shell: Sh
                    command: mvn compile
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: compile
                  identifier: compile
                  spec:
                    shell: Sh
                    command: mvn test
              - step:
                  type: Run
                  name: package
                  identifier: package
                  spec:
                    shell: Sh
                    command: mvn package
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
