pipeline:
  identifier: Build_rohannaik29_java_hello_world_with_maven_1701588761708
  name: Build java-hello-world-with-maven
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: rohannaik29/java-hello-world-with-maven
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
        tags: {}
  variables:
    - name: branch
      type: String
      description: ""
      required: false
      value: <+trigger.targetBranch>
    - name: spec
      type: String
      description: ""
      required: false
      value: <+pipeline.properties.ci.codebase.build.spec.branch>
    - name: BranchName
      type: String
      description: ""
      required: false
      value: <+pipeline.properties.ci.codebase.build.spec.branch>
